export const HOMEPAGE_ROUTE = "/"
export const SIGN_UP_ROUTE = "/sign_up"
export const SIGN_IN_ROUTE = "/sign_in"
export const TYPE_CODE_ROUTE = "/type_code"
export const PERSONAL_PAGE_ROUTE = "/personal"